### PR TITLE
Support for styles using resource keys in static properties

### LINKED ISSUE #1: Support for static property styles
Hi! Thanks for putting this together, really nice tool.

I needed to get the "sub styles" for the Toolbar control, such as `ToolBar.ButtonStyleKey` but Style Snooper only shows styles for types. It would be nice if Style Snooper could show also these styles. I will submit a PR shortly.

### PR DESCRIPTION
**Pull request by mgnslndh**
Refactored the code to also look at static properties on FrameworkElement for styles resource keys.

Fixes #1

### CODE REVIEW

**Comment by drewnoakes** [comment]
Code formatting changes make it really hard to see what's actually changed here.

**Comment by drewnoakes** [comment]
Can you include screenshots showing how the change looks in practice?

**Comment by mgnslndh** [comment]
Sorry about the formatting issues, I forgot about Xaml Styler being active. Do you want me to revert the XAML formatting changes?

The application does not look that much different. Instead of "Choose a type" I opted for "Choose a style" since it is no longer types the user is selecting from:

StyleSnooper

Mostly internal changes to accommodate for styles that are not defined by the default style key of a `FrameworkElement`.

**Comment by drewnoakes** [comment]
Thanks for the screenshot, and the PR.

In general, mixing formatting and functional changes in the same commit can create trouble down the line, especially if a bug is introduced by the commit. Ideally formatting changes are in their own PR.

**Comment by drewnoakes** [comment]
Published in https://github.com/drewnoakes/style-snooper/releases/tag/1.1

**Comment by mgnslndh** [comment]
Thanks!

Yes, I will have to take more care when I use tools like XamlStyler. They are nice to have but, yes, their usage can cause problems when random formatting changes mix with functional changes. Probably better to leave such tools off if they're not used by default on the code base.

**Pull request merged**
